version: '3.7'
services:
  auth-db:
    container_name: auth-db
    image: postgres:10-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: user.auth
      POSTGRES_PASSWORD: user.pass
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

