spring:
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true
    date-format: yyyy-MM-dd
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT-03:00
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/auth}
    username: ${DB_USER:user.auth}
    password: ${DB_PASSWORD:user.pass}
    hikari:
      maximum-pool-size: 10
      connection-timeout: 60000
  jpa:
    properties:
#      org:
#        hibernate:
#          envers:
#            audit_table_suffix: _auditoria
#            revision_field_name: id_revisao
#            revision_type_field_name: tipo_revisao
#            default_schema: auditoria
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  flyway:
    schemas: public

auth-service:
  security:
    oauth2:
      access-token:
        validity-seconds: ${OAUTH2_ACCESS_TOKEN_VALIDITY_SECONDS:1800}
      refresh-token:
        secure-cookie: ${OAUTH2_REFRESH_TOKEN_SECURE_COOKIE:false}
        validity-seconds: ${OAUTH2_REFRESH_TOKEN_VALIDITY_SECONDS:86400}
    jwt:
      signing-key: ${JWT_SIGNING_KEY:spring-auth-service}
